version: '3.1'
services:
  db:
    image: mariadb:10.11
    container_name: dbdev2
    #command: --default-authentication-plugin=mysql_native_password
    environment:
      MARIADB_ROOT_PASSWORD: devdb
      MARIADB_DATABASE: infra
      MARIADB_USER: db_user
      MARIADB_PASSWORD: db_user_pass
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
      #- ./mysql/:/etc/mysql
volumes:
  dbdata:
